
stages:
  - check
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update
  - apt-get install -y mosquitto-clients
  - mv fake_secrets.yaml secrets.yaml

check_config:
  stage: check
  image: homeassistant/home-assistant:latest
  script:
    - python -m homeassistant -c . --script check_config
