homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize: !include customise.yaml
  packages: !include_dir_named packages

http:
  api_password: !secret http_password 
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies: !secret reverse_proxy_ip

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend
conversation:

# System health
system_health:

# MQTT broker
mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  discovery: true
  discovery_prefix: homeassistant

#mqtt_eventstream:
#  publish_topic: !secret es_pub_topic
#  subscribe_topic: !secret es_sub_topic

device_tracker:
  - platform: snmp
    host: !secret firewall_host
    community: !secret firewall_snmp_community 
    baseoid: 1.3.6.1.2.1.4.22.1.2
    track_new_devices: no
#  - platform: owntracks
#    max_gps_accuracy: 200
#    waypoints: yes
#    waypoint_whitelist:
#      - rob_ot

map:

# not using this yet
#mysensors:
#  gateways:
#    - device: !secret mysensors_host
#      persistence_file: '/home/hass/.homeassistant/mysensors.json'
#      tcp_port: !secret mysensors_port
#  debug: true
#  persistence: true
#  version: '1.5'
#  optimistic: false

#zoneminder:
#  host: !secret zm_host
#  path: /zm/
#  ssl: False
#  username: !secret zm_username
#  password: !secret zm_password

#influxdb:
#  host: !secret influx_host
#  port: 8086
#  database: !secret influx_dbname
#  username: !secret influx_user
#  password: !secret influx_passwd

#google_assistant:
#  project_id: !secret ga_project_id
#  client_id: !secret ga_client_id
#  access_token: !secret ga_access_token
#  agent_user_id: !secret ga_agent_user_id
#  api_key:  !secret ga_api_key
#  exposed_domains:
#    - switch
#    - light
#    - fan
#  entity_config:
#    group.kitchen_downlights:
#      expose: true
#    scene.movie:
#      expose: true

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
    
cast:
  media_player:
    - host: !secret chromecast_host

# include entity files
input_boolean: !include entities/input_booleans.yaml
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
climate: !include entities/heating.yaml
light: !include entities/lights.yaml
switch: !include entities/switches.yaml
media_player: !include entities/media_players.yaml
#camera: !include entities/cameras.yaml
group: !include entities/groups.yaml
fan: !include entities/fans.yaml
timer: !include entities/timers.yaml

# include zones
zone: !include zones.yaml

# include automation related stuff
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automation/
notify: !include notify.yaml

