---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Internal and external URLs
  external_url: !secret base_url
  internal_url: !secret base_url
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize: !include customise.yaml
  packages: !include_dir_named packages
    
default_config:
  
logger:
  default: warn

http:
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies: !secret reverse_proxy_ip

websocket_api:

prometheus:
  namespace: hass

webhook:

mobile_app:

my:
  
stream:
  
media_source:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend
conversation:

# System health
system_health:

# MQTT broker
mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: "3.1.1"
  discovery: true
  discovery_prefix: homeassistant

#mqtt_eventstream:
#  publish_topic: !secret es_pub_topic
#  subscribe_topic: !secret es_sub_topic

#google_assistant:
#  project_id: !secret ga_project_id
#  client_id: !secret ga_client_id
#  access_token: !secret ga_access_token
#  agent_user_id: !secret ga_agent_user_id
#  api_key:  !secret ga_api_key
#  exposed_domains:
#    - switch
#    - light
#    - fan
#  entity_config:
#    group.kitchen_downlights:
#      expose: true
#    scene.movie:
#      expose: true

speedtestdotnet:

# include entity files
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
climate: !include entities/heating.yaml
light: !include entities/lights.yaml
switch: !include entities/switches.yaml
#camera: !include entities/cameras.yaml
group: !include entities/groups.yaml
fan: !include entities/fans.yaml
timer: !include entities/timers.yaml

# include zones
zone: !include zones.yaml

# include automation related stuff
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
automation: !include automations.yaml
notify: !include notify.yaml

