version: '3.9'

services:

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - /mnt/docker-data/mosquitto/config:/mosquitto/config
      - /mnt/docker-data/mosquitto/data:/mosquitto/data
      - /mnt/docker-data/mosquitto/logs:/mosquitto/logs

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - /mnt/docker-data/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
    restart: always
    network_mode: host

  homeassistant:
    image: homeassistant/home-assistant:2022.10
    volumes:
      - /mnt/docker-data/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mosquitto
      - influxdb
    restart: always
    network_mode: host

  nodered:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - /mnt/docker-data/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mosquitto
      - homeassistant
    restart: always

  #appdaemon:
  #  image: acockburn/appdaemon:4.0.3
  #  ports:
  #    - 5000:5000
  #  volumes:
  #    - /mnt/docker-data/appdaemon:/conf
  #    - /etc/localtime:/etc/localtime:ro
  #  depends_on:
  #    - homeassistant
  #  restart: always

  marytts:
    image: sliversniper/marytts
    ports:
      - 59125:59125
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-data/marytts/lib/voice-dfki-poppy-hsmm-5.2.jar:/marytts/marytts-5.1.2/lib/voice-dfki-poppy-hsmm-5.2.jar:ro
    restart: always

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - /mnt/docker-data/influxdb/data:/var/lib/influxdb2
      - /mnt/docker-data/influxdb/conf:/etc/influxdb2
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /mnt/docker-data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  tasmoadmin:
    image: raymondmm/tasmoadmin
    ports:
      - 5555:80
    volumes:
      - /mnt/docker-data/tasmoadmin:/data
    depends_on:
      - mosquitto
    restart: always

  #frigate:
  #  privileged: true
  #  restart: unless-stopped
  #  image: blakeblackshear/frigate:0.8.4-amd64
  #  devices:
  #    - /dev/bus/usb:/dev/bus/usb
  #    - /dev/dri/card0
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /mnt/docker-data/home-assistant/frigate.yaml:/config/config.yml:ro
  #    - /mnt/cctv/frigate:/media/frigate
  #    - type: tmpfs
  #      target: /tmp/cache
  #      tmpfs:
  #        size: 1000000000
  #  ports:
  #    - "1935:1935"
  #    - "5000:5000"
  #  env_file:
  #    - frigate.env
