---
- platform: group
  name: Kitchen Downlights
  entities:
    - light.kitchen_downlight_1
    - light.kitchen_downlight_2
    - light.kitchen_downlight_3

- platform: group
  name: Living Room Spots
  entities:
    - light.living_room_spot_1
    - light.living_room_spot_2
    - light.living_room_spot_3

- platform: group
  name: Dining Room Spots
  entities:
    - light.dining_room_spot_1
    - light.dining_room_spot_2
    - light.dining_room_spot_3

- platform: limitlessled
  bridges:
    - host: !secret limitlessled_host
      port: 8899
      version: 4
      groups:
        - number: 1
          name: Hallway
        - number: 2
          name: Toilet
        #- number: 4
        #  name: Dining Room Spots
