---
- platform: yeelight
  devices:
    !secret rl_host:
      name: Reading Lamp
    !secret kd1_host:
      name: Kitchen Downlight 1
    !secret kd2_host:
      name: Kitchen Downlight 2
    !secret kd3_host:
      name: Kitchen Downlight 3

- platform: group
  name: Kitchen Downlights
  entities:
    - light.yeelight_color1_34ce0084d85f
    - light.yeelight_color1_34ce0084fb1d
    - light.yeelight_color1_34ce008b7b7e

- platform: group
  name: Living Room Spots
  entities:
    - light.living_room_spot_1
    - light.living_room_spot_2
    - light.living_room_spot_3

- platform: group
  name: Dining Room Spots
  entities:
    - light.dining_room_spot_1
    - light.dining_room_spot_2
    - light.dining_room_spot_3

- platform: limitlessled
  bridges:
    - host: !secret limitlessled_host
      port: 8899
      version: 4
      groups:
        - number: 1
          name: Hallway
        - number: 2
          name: Toilet
        #- number: 4
        #  name: Dining Room Spots

- platform: mqtt
  name: "Night Light"
  state_topic: !secret nl_state_topic
  command_topic: !secret nl_command_topic
  payload_on: !secret nl_payload_on
  payload_off: !secret nl_payload_off
  optimistic: false
  retain: true
