---
#  - platform: zoneminder
#    name: zoneminder_sensor

- platform: cert_expiry
  host: !secret blog_host

- platform: cert_expiry
  host: !secret analytics_host

- platform: cert_expiry
  host: !secret news_host

- platform: cert_expiry
  host: !secret hass_host

- platform: cert_expiry
  host: !secret hass_host
