
- alias: 'Kettle off at night'
  trigger:
    platform: time
    minutes: 0
    hours: 23
    seconds: 0
  condition:
    condition: state
    entity_id: switch.kettle
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kettle
    - service: !secret notify_service1
      data:
        title: "Set up the Kettle"
        message: 'Remember to set up the kettle!'
