
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.gotify_1
    data:
      title: "Update Available"
      message: 'Update for Home Assistant is available.'

