  
- alias: 'Morning (Mon-Tue)'
  trigger:
    platform: time
    # mon & tue mornings at 7.00
    minutes: 0
    hours: 7
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
      - condition: state
        entity_id: group.presence
        state: home
      - condition: sun
        before: sunrise
        before_offset: "0:20:00" 
  action:
    service: script.turn_on
    entity_id: script.morning

- alias: 'Morning (Wed-Fri)'
  trigger:
    platform: time
    # wed, thurs, fri mornings at 6.45
    minutes: 45
    hours: 6
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - wed
          - thu
          - fri
      - condition: state
        entity_id: group.presence
        state: home
      - condition: sun
        before: sunrise
        before_offset: "0:20:00" 
  action:
    service: script.turn_on
    entity_id: script.morning

- alias: 'Lights off in morning'
  trigger:
    platform: time
    # weekday mornings at 7.25
    minutes: 25
    hours: 7
    seconds: 0
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: light.turn_off
    entity_id: light.main_lights

