
- alias: 'Set movie scene when watching TV in the evening'
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: playing
    - platform: state
      entity_id: media_player.living_room
      to: playing
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
  action:
      service: scene.turn_on
      entity_id: scene.movie

- alias: 'Bring up lights when movie paused'
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: paused
    - platform: state
      entity_id: media_player.tv
      to: idle
    - platform: state
      entity_id: media_player.living_room
      to: paused
    - platform: state
      entity_id: media_player.living_room
      to: idle
    - platform: state
      entity_id: media_player.living_room
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.downlights_bright
