
- alias: 'Set movie scene when watching TV in the evening'
  trigger:
    platform: state
    entity_id: media_player.tv
    state: playing
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
  action:
      service: scene.turn_on
      entity_id: scene.movie

- alias: 'Bring up lights when movie paused'
  trigger:
    - platform: state
      entity_id: media_player.tv
      state: paused
    - platform: state
      entity_id: media_player.tv
      state: stopped
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.main_lights_bright


