
- alias: 'Set movie scene when watching TV in the evening'
  trigger:
    - platform: state
      entity_id: media_player.living_room_kodi
      to: playing
    - platform: state
      entity_id: media_player.chromecast
      to: playing
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
      - condition: template
        value_template: '{{ states.media_player.tv.attributes.media_content_type != "music" }}'
      - condition: template
        value_template: '{{ states.media_player.tv.attributes.media_title != "Home And Away" }}'
  action:
      service: scene.turn_on
      entity_id: scene.movie

- alias: 'Bring up lights when movie paused'
  trigger:
    - platform: state
      entity_id: media_player.living_room_kodi
      to: paused
    - platform: state
      entity_id: media_player.living_room_kodi
      to: idle
    - platform: state
      entity_id: media_player.chromecast
      to: paused
    - platform: state
      entity_id: media_player.chromecast
      to: idle
    - platform: state
      entity_id: media_player.chromecast
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: time
        after: '20:00:00'
  action:
    service: script.turn_on
    entity_id: script.downlights_bright

