
- alias: 'Lights on at sunset, sunny days'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:20:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.presence
        state: home
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        below: 49
  action:
    service: light.turn_on
    entity_id: light.main_lights
    data:
      brightness: 255
      rgb_color: [255, 255, 255]
      
- alias: 'Lights on at sunset, cloudy days'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:40:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.presence
        state: home
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 50
  action:
    service: light.turn_on
    entity_id: light.main_lights
    data:
      brightness: 255
      rgb_color: [255, 255, 255]

- alias: 'Lights on if someone comes home, after sunset'
  trigger:
    - platform: state
      entity_id: group.presence
      from: 'not_home'
      to: 'home'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-00:20:00"
  action:
    service: light.turn_on
    entity_id: light.main_lights
    data:
      brightness: 255
      rgb_color: [255, 255, 255]

