
- alias: 'Switch on kitchen downlights'
  trigger:
    platform: mqtt
    topic: !secret sc_topic
    payload: !secret sc_b1_payload
  action:
    service: script.turn_on
    data:
      entity_id: script.downlights_bright

- alias: 'Switch off kitchen downlights'
  trigger:
    platform: mqtt
    topic: !secret sc_topic
    payload: !secret sc_b2_payload
  action:
    service: light.turn_off
    data:
      entity_id: light.kitchen_downlights

