
- alias: 'Switch on kitchen downlights'
  trigger:
    platform: mqtt
    topic: !secret sc_topic
    payload: !secret sc_b1_payload
  action:
    service: scene.turn_on
    data:
      entity_id: scene.downlights_bright

- alias: 'Switch off kitchen downlights'
  trigger:
    platform: mqtt
    topic: !secret sc_topic
    payload: !secret sc_b2_payload
  action:
    service: homeassistant.turn_off
    data:
      entity_id: group.kitchen_downlights

