---
automation:
  - alias: "Electric blankets prompt"
    id: electric_blankets_prompt
    trigger:
      platform: time
      at: "21:30:00"
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.weather_station_temperature
          below: 10.0
        - condition: state
          entity_id: input_boolean.away_mode
          state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: group.electric_blankets
      - service: !secret notify_entity1
        data:
           title: "It's cold tonight!"
           message: "Go and make sure the electric blankets are turned on."
