---
# vim: set filetype=home-assistant :
# vim: set syntax=yaml :
switch:
  platform: kankun
  switches:
    camera_power:
      host: !secret camera_power_host

binary_sensor:
  - platform: ping
    name: "Driveway Camera Status"
    host: !secret cam0_host
    scan_interval: 10
  - platform: ping
    name: "Front Lawn Camera Status"
    host: !secret cam1_host
    scan_interval: 10
  - platform: ping
    name: "Side Passage Camera Status"
    host: !secret cam2_host
    scan_interval: 10
  - platform: ping
    name: "Back Passage Camera Status"
    host: !secret cam3_host
    scan_interval: 10
  - platform: ping
    name: "Patio Camera Status"
    host: !secret cam4_host
    scan_interval: 10
  - platform: ping
    name: "Side Lawn Camera Status"
    host: !secret cam5_host
    scan_interval: 10

automation:
  - alias: Reset cameras if connectivity lost
    trigger:
      - platform: state
        entity_id: binary_sensor.driveway_camera_status
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.front_lawn_camera_status
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.side_passage_camera_status
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.back_passage_camera_status
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.patio_camera_status
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.side_lawn_camera_status
        to: "off"
        for:
          minutes: 2
    action:
      - service: switch.turn_off
        entity_id: switch.camera_power
      - delay: 30
      - service: switch.turn_on
        entity_id: switch.camera_power
