---
# vim: set filetype=home-assistant :
# vim: set syntax=yaml :
input_boolean:
  christmas_mode:
    name: Christmas Mode
    icon: mdi:string-lights

automation:
  - id: auto_enable_christmas_mode
    alias: "Auto-enable Christmas Mode"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().day == 1 and now().month == 12 }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.christmas_mode

  - id: auto_disable_christmas_mode
    alias: "Auto-disable Christmas Mode"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().day == 7 and now().month == 1 }}"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.christmas_mode

  - id: christmas_tree_on_afternoon
    alias: "Turn on Christmas tree in the afternoon if we're home"
    trigger:
      - platform: time
        at: "15:30:00"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.christmas_mode
            state: "on"
          - condition: state
            entity_id: input_boolean.away_mode
            state: "off"
    action:
      - service: light.turn_on
        target:
          entity_id: light.christmas_tree
      - service: select.select_option
        target:
          entity_id: select.christmas_tree_preset
        data:
          option: Rainbow Twinkle

  - id: christmas_tree_on_morning
    alias: "Turn on Christmas tree in the morning if we're home"
    trigger:
      - platform: time
        at: "07:45:00"
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.christmas_mode
            state: "on"
          - condition: state
            entity_id: input_boolean.away_mode
            state: "off"
    action:
      - service: light.turn_on
        target:
          entity_id: light.christmas_tree
      - service: select.select_option
        target:
          entity_id: select.christmas_tree_preset
        data:
          option: Rainbow Twinkle
