---
shell_command:
  desktop_power_on: !secret desktop_command_on
  desktop_power_off: !secret desktop_command_off

binary_sensor:
  - platform: ping
    name: "Desktop Computer State"
    host: !secret desktop_host
    count: 1
    scan_interval: 5

switch:
  - platform: template
    switches:
      desktop_computer_power:
        value_template: "{{ is_state('binary_sensor.desktop_computer_state', 'on') }}"
        turn_on:
          service: shell_command.desktop_power_on
        turn_off:
          service: shell_command.desktop_power_off
