---
rest_command:
  wake_work_computer:
    url: !secret opnsense_wol_url
    method: POST
    payload: '{"wake":{"interface": "opt9", "mac": "fc:4d:d4:39:6b:d7"}}'
    content_type: 'application/json'
    username: !secret opnsense_user
    password: !secret opnsense_key
    verify_ssl: false

binary_sensor:
  - platform: ping
    name: "Work Computer"
    host: !secret work_machine
    count: 1
    scan_interval: 5

#switch:
#  - platform: template
#    switches:
#      work_computer_power:
#        value_template: "{{ is_state('binary_sensor.work_computer', 'on') }}"
#        turn_on:
#          service: rest_command.wake_work_computer

script:
  wake_work_computer:
    alias: "Wake Work Computer"
    sequence:
      - service: rest_command.wake_work_computer
