---
# vim: set filetype=home-assistant :
# vim: set syntax=yaml :
input_select:
  home_mode:
    name: "Home Mode"
    options:
      - "None"
      - "Coffee Time!"
      - "Lunchtime"
      - "Evening"
      - "Bedtime"
      - "Night"

script:
  home_mode:
    alias: Home Mode Switch
    sequence:
      - alias: Select Home Mode
        service: input_select.select_option
        data_template:
          entity_id: input_select.home_mode
          option: >
            {% if now().hour < 7 %}
            Bedtime
            {% elif now().hour < 12 %}
            Coffee Time!
            {% elif now().hour < 18 %}
            Lunchtime
            {% elif now().hour < 22 %}
            Evening
            {% else %}
            Bedtime
            {% endif %}

automation:
  - alias: Switch Home Mode from NFC tag
    id: home_mode_nfc
    trigger:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: a1bd5e14-ae40-48cf-8005-d3a2c9a19efe
    action:
      service: script.home_mode

  - alias: Coffee/Lunchtime Lights
    id: coffee_lunchtime_lights
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Coffee Time!"
      - platform: state
        entity_id: input_select.home_mode
        to: "Lunchtime"
    action:
      - service: script.turn_on
        entity_id: script.downlights_bright

  - alias: End of Coffee/Lunch Time
    id: end_coffee_lunchtime
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Coffee Time!"
        for:
          minutes: 20
      - platform: state
        entity_id: input_select.home_mode
        to: "Lunchtime"
        for:
          hours: 1
    action:
      - service: light.turn_off
        entity_id: light.kitchen_downlights
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: None

  - alias: Evening
    id: home_mode_evening
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Evening"
    action:
      - service: automation.trigger
        entity_id: automation.toilet_lights_dim
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: None

  - alias: Bedtime
    id: home_mode_bedtime
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Bedtime"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: Night
      - service: script.enable_camera_detect
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.tts_enabled
      - service: scene.turn_on
        data:
          entity_id: scene.goodnight
      - service: switch.turn_off
        target:
          entity_id: switch.kettle
      - service: switch.turn_off
        target:
          entity_id: switch.photo_frame_power
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      - service: light.turn_off
        target:
          entity_id: light.christmas_tree
      #- delay:
      #   minutes: 10
      #- service: switch.turn_off
      #  data:
      #    entity_id: group.electric_blankets

