---
media_player:
  - platform: snapcast
    host: !secret musicserver_host
  - platform: mpd
    host: !secret musicserver_host
    name: Mopidy

binary_sensor:
  - platform: command_line
    name: "Living Room Netflix"
    command: !secret living_room_netflix_command
    device_class: connectivity

switch:
  - platform: mqtt
    name: "Living Room TV"
    command_topic: "tv/livingroom/cec/0/cmd"
    payload_on: "on"
    payload_off: "off"
    state_topic: "tv/livingroom/cec/0"
    availability_topic: "tv/livingroom/bridge/status"

automation:
  - alias: "Mute outdoor speakers when powered down"
    id: mute_outdoor_speakers
    trigger:
      platform: state
      entity_id: switch.outdoor_speakers
      from: "on"
      to: "off"
    action:
      service: media_player.volume_mute
      data:
        entity_id: media_player.snapcast_client_outdoor_speakers
        is_volume_muted: true

  - alias: "Unmute outdoor speakers when powered up"
    id: unmute_outdoor_speakers
    trigger:
      platform: state
      entity_id: switch.outdoor_speakers
      from: "off"
      to: "on"
    action:
      service: media_player.volume_mute
      data:
        entity_id: media_player.snapcast_client_outdoor_speakers
        is_volume_muted: false

  - alias: 'Turn off TV if idle for 5 minutes'
    id: tv_idle_off
    trigger:
      - platform: state
        entity_id: media_player.living_room_kodi
        to: idle
        for:
          minutes: 5
      - platform: state
        entity_id: binary_sensor.living_room_netflix
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.living_room_kodi
          state: idle
        - condition: state
          entity_id: binary_sensor.living_room_netflix
          state: 'off'
        - condition: time
          after: '20:00:00'
          before: '07:00:00'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.living_room_tv
      - condition: and
        conditions:
          - condition: state
            entity_id: light.living_room_spots
            state: 'on'
          - condition: template
            value_template: '{{ states.light.living_room_spots.attributes.rgb_color == [0, 0, 255] or states.light.living_room_spots.attributes.rgb_color == (0, 0, 255) }}'
      - service: light.turn_off
        data:
          entity_id: light.living_room_spots