---
automation:
  - alias: 'Set movie scene when watching TV in the evening'
    id: movie_start_lights
    trigger:
      - platform: state
        entity_id: media_player.living_room_kodi
        to: playing
      - platform: state
        entity_id: media_player.living_room_tv
        to: playing
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: time
          after: '20:00:00'
        - condition: template
          value_template: '{{ states.media_player.living_room_kodi.attributes.media_content_type != "music" }}'
        - condition: template
          value_template: '{{ states.media_player.living_room_kodi.attributes.media_title != "Home And Away" }}'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.movie

  - alias: 'Bring up lights when movie paused'
    id: movie_pause_lights
    trigger:
      - platform: state
        entity_id: media_player.living_room_kodi
        to: paused
      - platform: state
        entity_id: media_player.living_room_kodi
        to: idle
      - platform: state
        entity_id: media_player.living_room_tv
        to: paused
      - platform: state
        entity_id: media_player.living_room_tv
        to: idle
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: time
          after: '20:00:00'
    action:
      service: script.turn_on
      entity_id: script.downlights_bright
