---
# vim: set filetype=home-assistant :
# vim: set syntax=yaml :
automation:
  - alias: "Night mode kitchen light on"
    id: night_mode_kitchen_light_on
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_hall_door_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Night"
    action:
      - alias: Lights to Goodnight Scene
        service: scene.turn_on
        data:
          entity_id: scene.goodnight

  - alias: "Night mode kitchen light off"
    id: night_mode_kitchen_light_off
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_hall_door_contact
        from: "on"
        to: "off"
        for:
          seconds: 5
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Night"
    action:
      - alias: Light Off
        service: light.turn_off
        entity_id: light.kitchen_downlight_2
