---
sun:


sensor:
  - platform: moon

  - platform: command_line
    name: North Taranaki Webcam URL
    scan_interval: 900
    command: "/config/shell_commands/tac_webcam.py"

camera:
  - platform: generic
    name: North Taranaki Webcam
    still_image_url: "{{ states.sensor.north_taranaki_webcam_url.state }}"
    limit_refetch_to_url_change: true
  - platform: generic
    name: Fitzroy Beach Webcam
    still_image_url: "https://www.primowireless.co.nz/webcameras/snapshot_fitzboardriders_sth.jpg"

binary_sensor:
  - platform: iss
