---
map:

input_boolean:
  away_mode:
    name: Away Mode
    icon: mdi:account-council
  vacation_mode:
    name: Vacation Mode
    icon: mdi:castle

automation:
  - alias: "Activate Away Mode"
    trigger:
      - platform: state
        entity_id: person1_entity
        from: 'home'
        for:
          minutes: 5
      - platform: state
        entity_id: person2_entity
        from: 'home'
        for:
          minutes: 5
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: person1_entity
          state: 'home'
        - condition: state
          entity_id: person2_entity
          state: 'home'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.outdoor_speakers
      - service: switch.turn_off
        data:
          entity_id: switch.living_room_tv_fused
      - service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_tv
      - service: homeassistant.turn_off
        data:
          entity_id: group.lights
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.away_mode

  - alias: "Deactivate Away Mode"
    trigger:
      - platform: state
        entity_id: person1_entity
        to: 'home'
      - platform: state
        entity_id: person2_entity
        to: 'home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.away_mode
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.vacation_mode
