---
map:

input_boolean:
  away_mode:
    name: Away Mode
    icon: mdi:account-council
  vacation_mode:
    name: Vacation Mode
    icon: mdi:castle

automation:
  - alias: "Activate Away Mode"
    id: away_mode_activate
    trigger:
      - platform: state
        entity_id: !secret person1_entity
        from: 'home'
        for:
          minutes: 5
      - platform: state
        entity_id: !secret person2_entity
        from: 'home'
        for:
          minutes: 5
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: !secret person1_entity
          state: 'home'
        - condition: state
          entity_id: !secret person2_entity
          state: 'home'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.outdoor_speakers
      - service: switch.turn_off
        data:
          entity_id: switch.living_room_tv
      - service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_tv
      - service: switch.turn_off
        target:
          entity_id: switch.photo_frame_power
      - service: homeassistant.turn_off
        data:
          entity_id: group.lights
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.away_mode
      - condition: state
        entity_id: input_boolean.christmas_mode
        state: "on"
      - service: light.turn_off
        target:
          entity_id: light.christmas_tree

  - alias: "Deactivate Away Mode"
    id: away_mode_deactivate
    trigger:
      - platform: state
        entity_id: !secret person1_entity
        to: 'home'
      - platform: state
        entity_id: !secret person2_entity
        to: 'home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.away_mode
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.vacation_mode
      - service: switch.turn_on
        target:
          entity_id: switch.photo_frame_power
