---
automation:
  - alias: "Shed Lights Timeout"
    id: shed_lights_timeout
    trigger:
      - platform: state
        entity_id: light.shed_lights
        to: "on"
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.shed_lights
