
shell_command:
  restart_kodi: /home/homeassistant/.homeassistant/shell_commands/restart_kodi.sh

script:
  restart_kodi:
    alias: "Restart Kodi"
    sequence:
      - alias: "Execute restart command"
        service: shell_command.restart_kodi

binary_sensor:
  - platform: mqtt
    name: "Open MQTT Gateway Status"
    state_topic: "home/OpenMQTTGateway/LWT"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
  - platform: mqtt
    name: "Node-RED Eomer Status"
    state_topic: "nodered/eomer/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
  - platform: mqtt
    name: "Node-RED Fili Status"
    state_topic: "nodered/fili/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
  - platform: mqtt
    name: "Node-RED Balin Status"
    state_topic: "nodered/balin/status"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
  - platform: mqtt
    name: "Zigbee2mqtt Status"
    state_topic: "zigbee2mqtt/bridge/state"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"

sensor:
  - platform: mqtt
    name: "Test Battery"
    state_topic: test/battery
    unit_of_measurement: '%'
  - platform: template
    sensors:
      kitchen_button_battery:
        friendly_name: "Kitchen Button Battery"
        unit_of_measurement: "%"
        value_template: "{{ states.sensor.kitchen_button.attributes.battery }}"
      toilet_button_battery:
        friendly_name: "Toilet Button Battery"
        unit_of_measurement: "%"
        value_template: "{{ states.sensor.toilet_button.attributes.battery }}"

automation:
  - alias: Low Battery Notification
    trigger:
      - platform: numeric_state
        entity_id: sensor.test_battery
        below: 20
      - platform: numeric_state
        entity_id: !secret bed1_battery_entity
        below: 20
      - platform: numeric_state
        entity_id: !secret bed2_battery_entity
        below: 20
      - platform: numeric_state
        entity_id: sensor.kitchen_hall_door_battery
        below: 20
      - platform: numeric_state
        entity_id: sensor.kitchen_button_battery
        below: 20
      - platform: numeric_state
        entity_id: sensor.toilet_button_battery
        below: 20
    action:
      service: notify.notify
      data_template:
        title: "Low Battery Alert"
        message: "Device '{{ trigger.to_state.name }}' has LOW battery: {{ trigger.to_state.state }}%."
  - alias: Critical Battery Notification
    trigger:
      - platform: numeric_state
        entity_id: sensor.test_battery
        below: 5
      - platform: numeric_state
        entity_id: !secret bed1_battery_entity
        below: 5
      - platform: numeric_state
        entity_id: !secret bed2_battery_entity
        below: 5
      - platform: numeric_state
        entity_id: sensor.kitchenhall_door_battery
        below: 5
      - platform: numeric_state
        entity_id: sensor.kitchen_button_battery
        below: 5
      - platform: numeric_state
        entity_id: sensor.toilet_button_battery
        below: 5
    action:
      service: notify.notify
      data_template:
        title: "Critical Battery Alert"
        message: "Device '{{ trigger.to_state.name }}' has CRITICAL battery: {{ trigger.to_state.state }}%."

  - alias: Auto-reset Room Sensors
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_sensor_status
        to: "off"
        for: "00:10:00"
    action:
      - service: switch.turn_off
        entity_id: switch.room_sensors
      - delay:
          seconds: 30
      - service: switch.turn_on
        entity_id: switch.room_sensors
      - service: notify.notify
        data_template:
          title: "Room Sensors Reset"
          message: "Device '{{ trigger.to_state.name }}' was offline for 10 minutes, room sensors reset."

