---
timer:
  toothbrush_charger_timeout:
    duration: "16:00:00"

automation:
  - alias: Charge toothbrushes
    trigger:
      platform: time
      at: "22:30:00"
    condition:
      condition: template
      value_template: "{% if now().day % 5 == 0 %}true{% else %}false{% endif %}"
    action:
      - service: switch.turn_on
        entity_id: switch.adults_toothbrush_charger
      - service: switch.turn_on
        entity_id: switch.kids_toothbrush_charger
      - service: timer.start
        entity_id: timer.toothbrush_charger_timeout

  - alias: Turn off toothbrushes when charged
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.toothbrush_charger_timeout
    action:
      - service: switch.turn_off
        entity_id: switch.adults_toothbrush_charger
      - service: switch.turn_off
        entity_id: switch.kids_toothbrush_charger
