---
# vim: set filetype=home-assistant :
# vim: set syntax=yaml :
automation:
  - alias: Notify on HACS updates
    id: update_notify_hacs
    trigger:
      - platform: state
        entity_id: sensor.hacs
    action:
      - service: notify.smtp_notify1
        data:
          title: "[homeassistant] HACS Update(s) available"
          message: "There are {{ trigger.to_state.state }} HACS updates available."

  - alias: Notify on HASS core update
    id: update_notify_core
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        to: "on"
    action:
      - service: notify.smtp_notify1
        data:
          title: "[homeassistant] HASS Core Update Available"
          message: >
            New Home Assistant core release available: {{
            states[trigger.to_state.domain][trigger.to_state.object_id].attributes.newest_version
            }}.

            Release notes: [{{
            states[trigger.to_state.domain][trigger.to_state.object_id].attributes.release_notes
            }}]({{
            states[trigger.to_state.domain][trigger.to_state.object_id].attributes.release_notes
            }})