---
neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_client_secret

script:
  spot_clean:
    alias: "Spot Clean"
    sequence:
      - alias: "Start spot clean"
        service: neato.custom_cleaning
        data:
          entity_id: vacuum.marvin
          mode: 2
          category: 3

  house_clean:
    alias: "House Clean"
    sequence:
      - alias: "Start house clean"
        service: neato.custom_cleaning
        data:
          entity_id: vacuum.marvin
          mode: 1
          category: 2

automation:
  - alias: "Schedule vacuum Monday and Friday"
    id: vacuum_schedule_mon_fri
    trigger:
      - platform: time
        at: "09:10:00"
    condition:
      - condition: time
        weekday:
          - mon
          - fri
    action:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.marvin
          mode: 1
          category: 2

  - alias: "Schedule vacuum early Saturday morning"
    id: vacuum_schedule_sat
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: time
        weekday:
          - sat
    action:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.marvin
          mode: 1
          category: 2

  - alias: "Vacuum Started Notification"
    id: vacuum_started_notification
    trigger:
      - platform: state
        entity_id: vacuum.marvin
        to: "cleaning"
    action:
      - service: notify.family
        data:
          title: "Vacuum Started"
          message: "Don't Panic! Marvin the Paranoid Vacuum Cleaner has started his run."

  - alias: "Vacuum Stopped Notification"
    id: vacuum_stopped_notification
    trigger:
      - platform: state
        entity_id: vacuum.marvin
        from: "cleaning"
        to: "docked"
    action:
      - service: notify.family
        data:
          title: "Vacuum Returned to Dock"
          message: "Don't Panic! Marvin the Paranoid Vacuum Cleaner has finished his run (for now)."

  - alias: "Vacuum Error Notification"
    id: vacuum_error_notification
    trigger:
      - platform: state
        entity_id: vacuum.marvin
        to: "error"
    action:
      - service: notify.family
        data:
          title: "Vacuum Error"
          message: >
            Uh oh! Looks like Marvin is in trouble.

            Status: {{ states.vacuum.marvin.attributes.status }}