---
zoneminder:
  host: !secret zm_host
  path: /zm/
  ssl: False
  username: !secret zm_username
  password: !secret zm_password

camera:
  - platform: zoneminder

automation:
  - alias: "Set run mode to ARMED-AWAY when we are away"
    trigger:
      - platform: state
        entity_id:
          - !secret person1_entity
          - !secret person2_entity
        from: "home"
        to: "away"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: !secret person1_entity
          state: "away"
        - condition: state
          entity_id: !secret person2_entity
          state: "away"
    action:
      - service: zoneminder.set_run_state
        name: "armed-away"
      - service: notify.gotify_1
        data:
          title: "Away mode enabled"
          message: "Cameras set to ARMED-AWAY"

  - alias: "Set run mode to ARMED-HOME when we are away"
    trigger:
      - platform: state
        entity_id:
          - !secret person1_entity
          - !secret person2_entity
        from: "away"
        to: "home"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: !secret person1_entity
          state: "home"
        - condition: state
          entity_id: !secret person2_entity
          state: "home"
    action:
      - service: zoneminder.set_run_state
        name: "armed-home"
      - service: notify.gotify_1
        data:
          title: "Home mode enabled"
          message: "Cameras set to ARMED-HOME"
